// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wweihgiklnxetpqcpyyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZWloZ2lrbG54ZXRwcWNweXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzcxMzksImV4cCI6MjA1MTIxMzEzOX0.MGXo-JjykqeUfnD6Zb7yhj6Klz7Wr1JND9WLpffnjUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);